version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot_image
    container_name: chatbot_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data/sqlite:/app/db_data  # persist DB here
    environment:
      - DJANGO_DB_PATH=/app/db_data/db.sqlite3
    restart: always
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]


# =========== for manual migration and running ===========

#version: '3.9'
#
#services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: chatbot_image
#    container_name: chatbot_app
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    restart: always
#    command: tail -f /dev/null   # ðŸ‘ˆ This line keeps the container running
